# Generated by Django 5.0.3 on 2024-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareTesting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='Id',
        ),
        migrations.AlterField(
            model_name='metrics',
            name='ClassName',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
